server:
  port: 21000
spring:
  application:
    name: 'customer_server_21000'
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.197.220:3306/elm?createDatabaseIfNotExist=true
    username: yxy
    password: yxy913949yxy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka: #这里都是发给服务注册中心看的
  instance:
    prefer-ip-address: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
    lease-renewal-interval-in-seconds: 5 #5秒时间，互动一次，sayHi
    lease-expiration-duration-in-seconds: 15 #
  client:
    service-url: #因为eureka是集群，所以 ， 连接
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/"
resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration:
          nanos: 1
        cancel-running-future: true
    instances:
      backendA:
        base-config: default
